[2025-10-02T14:37:22.226+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T14:37:22.244+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.run_pyspark_postgres manual__2025-10-02T14:37:20.783894+00:00 [queued]>
[2025-10-02T14:37:22.251+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.run_pyspark_postgres manual__2025-10-02T14:37:20.783894+00:00 [queued]>
[2025-10-02T14:37:22.252+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-02T14:37:22.264+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_pyspark_postgres> on 2025-10-02 14:37:20.783894+00:00
[2025-10-02T14:37:22.272+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=14882) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-02T14:37:22.273+0000] {standard_task_runner.py:63} INFO - Started process 14884 to run task
[2025-10-02T14:37:22.274+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'main', 'run_pyspark_postgres', 'manual__2025-10-02T14:37:20.783894+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp1fa23d53']
[2025-10-02T14:37:22.276+0000] {standard_task_runner.py:91} INFO - Job 122: Subtask run_pyspark_postgres
[2025-10-02T14:37:22.314+0000] {task_command.py:426} INFO - Running <TaskInstance: main.run_pyspark_postgres manual__2025-10-02T14:37:20.783894+00:00 [running]> on host 5adecdfd8c83
[2025-10-02T14:37:22.386+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='run_pyspark_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T14:37:20.783894+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T14:37:20.783894+00:00'
[2025-10-02T14:37:22.387+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T14:37:28.042+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T14:37:28.044+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 74, in read_from_postgres
    df.show()
    ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'show'
[2025-10-02T14:37:28.097+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=main, task_id=run_pyspark_postgres, run_id=manual__2025-10-02T14:37:20.783894+00:00, execution_date=20251002T143720, start_date=20251002T143722, end_date=20251002T143728
[2025-10-02T14:37:28.117+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 122 for task run_pyspark_postgres ('DataFrame' object has no attribute 'show'; 14884)
[2025-10-02T14:37:28.142+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-02T14:37:28.161+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T14:37:28.167+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
